#!/bin/bash
DIR=$(dirname "$0")

clear
ANSI_ART=$(cat <<EOF
\e[0;m              \e[0;40m  \e[48;5;240m  \e[0;40m  \e[0;m            \e[0;m
\e[0;m            \e[0;40m  \e[48;5;240m  \e[0;40m      \e[0;m          \e[0;m
\e[0;m            \e[48;5;254m  \e[0;40m    \e[48;5;254m  \e[0;40m  \e[0;m          \e[0;m
\e[0;m            \e[48;5;240m  \e[48;5;220m  \e[48;5;228m  \e[48;5;240m  \e[0;40m  \e[0;m          \e[0;m
\e[0;m            \e[48;5;220m        \e[0;40m  \e[0;m          \e[0;m
\e[0;m            \e[0;40m  \e[48;5;252m      \e[0;40m    \e[0;m        \e[0;m
\e[0;m          \e[0;40m    \e[48;5;254m      \e[0;40m    \e[0;m        \e[0;m
\e[0;m          \e[0;40m    \e[48;5;254m      \e[0;40m      \e[0;m      \e[0;m
\e[0;m        \e[0;40m    \e[48;5;240m  \e[48;5;254m      \e[0;40m  \e[48;5;240m  \e[0;40m    \e[0;m    \e[0;m
\e[0;m      \e[0;40m    \e[48;5;240m  \e[48;5;252m  \e[48;5;254m      \e[48;5;252m  \e[0;40m  \e[48;5;240m  \e[0;40m  \e[0;m    \e[0;m
\e[0;m      \e[0;40m    \e[48;5;240m  \e[48;5;252m  \e[48;5;254m      \e[48;5;252m  \e[0;40m  \e[48;5;240m  \e[0;40m    \e[0;m  \e[0;m
\e[0;m  \e[48;5;172m        \e[0;40m  \e[48;5;252m  \e[48;5;254m      \e[48;5;252m  \e[0;40m  \e[48;5;240m  \e[0;40m    \e[0;m  \e[0;m
\e[48;5;172m  \e[48;5;228m      \e[48;5;172m  \e[48;5;240m  \e[0;40m  \e[48;5;252m      \e[48;5;172m      \e[48;5;240m  \e[48;5;172m  \e[0;m  \e[0;m
\e[48;5;172m  \e[48;5;220m      \e[48;5;228m  \e[48;5;172m  \e[48;5;240m  \e[0;40m      \e[48;5;172m  \e[48;5;228m      \e[48;5;172m  \e[0;m  \e[0;m
\e[0;m  \e[48;5;172m  \e[48;5;220m      \e[48;5;228m  \e[48;5;172m  \e[48;5;240m      \e[48;5;172m  \e[48;5;228m  \e[48;5;220m      \e[48;5;172m  \e[0;m
\e[0;m    \e[48;5;172m        \e[0;m          \e[48;5;172m        \e[0;m  \e[0;m
EOF
)
printf "$ANSI_ART\n"

cd $DIR

# Use find to locate the .xcodeproj file
xcodeproj_file=$(find . -name "*.xcodeproj" -print -quit)

# Check if a .xcodeproj file was found
if [ -n "$xcodeproj_file" ]; then
    xcodeproj_name=$(basename "$xcodeproj_file" .xcodeproj)
else
    echo "No .xcodeproj file found."
    read
    # Close the Terminal window
    osascript -e 'tell application "Terminal" to close window 1' & exit
fi


# Compiling Code...
if [ ! -d "bin" ]; then
    mkdir bin
fi
if [ ! -d "bin/linux" ]; then
    mkdir bin/linux
fi
if [ ! -d "bin/linux/x86_64" ]; then
    mkdir bin/linux/x86_64
fi
if [ ! -d "bin/linux/aarch64" ]; then
    mkdir bin/linux/aarch64
fi

echo "Compiling Code..."
zig c++ -target x86_64-linux-gnu -std=c++20 -o bin/linux/x86_64/$xcodeproj_name src/*.cpp -s
zig c++ -target aarch64-linux-gnu -std=c++20 -o bin/linux/aarch64/$xcodeproj_name src/*.cpp -s

zip linux.zip bin/linux/* -r -x "*/.DS_Store"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
