#!/bin/bash
DIR=$(dirname "$0")
cd $DIR
clear

# Code Signing...
echo "Code Signing... Please wait!"

IDENTITY=$(security find-identity -v -p codesigning | grep "Developer ID Application" | awk '{print $2}')
codesign -s "$IDENTITY" ./build/*

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
