#!/bin/bash
DIR=$(dirname "$0")
printf '\e[1;40;92m'
clear

cd $DIR

echo "WWW"

www=/usr/local/var/www
cp pplib.zip $www/downloads/hp/pplib.zip
cp hpprgm.zip $www/downloads/hp/hpprgm.zip
cp macos.zip $www/downloads/macos/hp/p+.zip
cp linux.zip $www/downloads/linux/hp/p+.zip
cp windows.zip $www/downloads/pc/hp/p+.zip

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
