#!/bin/bash
DIR=$(dirname "$0")
clear
cd $DIR

#!/bin/bash

pkgbuild --root package-root \
         --identifier uk.insoft.primeplus \
         --version 1.0 --install-location / \
         --scripts scripts \
         PrimePlus.pkg
 
IDENTITY=$(security find-identity -v -p basic | grep "Developer ID Installer" | awk '{print $2}')
productsign --sign "$IDENTITY" PrimePlus.pkg PrimePlus-signed.pkg

rm -rf PrimePlus.pkg
mv PrimePlus-signed.pkg PrimePlus.pkg

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
